; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Thêm 2 dòng này để mạch tự động chạy ngay khi mở Terminal
monitor_rts = 0
monitor_dtr = 0

;Cấu hình tốc độ truyền dữ liệu qua cổng Serial Monitor
monitor_speed = 115200

; Khai báo thư viện chuẩn từ PlatformIO Registry 
; Tránh lỗi MissingPackageManifestError
lib_deps = 
    adafruit/Adafruit MLX90640 @ ^1.1.1
    adafruit/Adafruit BusIO @ ^1.14.1
    SPI
    Wire

; Các cờ biên dịch để tối ưu hóa bộ nhớ và FreeRTOS
build_flags = 
    -D CORE_DEBUG_LEVEL=1